### ISSUE TITLE
[wishlist] Switch user by click or doubleclick on big avatar image

### ISSUE THREAD

**Issue by feinstaub** [sddm/sddm#1007]
When "Switch User" is activated there is a screen with big avatars for logged-in users and a PLUS symbol. Below there is a "Cancel" and "Switch" button.

I regularly find myself wanting to click on the avatar image to activate the corresponding session.

Suggestions:
1) Double-click on an avatar image does the same as the Switch button.
2) When an avatar image is pre-selected, a single-click is enough to trigger the Switch action.

**Comment by davidedmundson** [comment]
SDDM doesn't have a switch user.

**Comment by piotr-dobrogost** [comment]
@feinstaub 
Switching user is handled by **Window** Manager (https://wiki.archlinux.org/index.php/Window_manager) and SDDM is **Display** Manager (https://wiki.archlinux.org/index.php/display_manager) and handles logging user in.
Screens presented by both are often by purpose designed so that they are aligned visually.
