### ISSUE TITLE
Feature request: Netork Connection Status on the login screen

### ISSUE THREAD

**Issue by saidbakr** [sddm/sddm#1105]
I suggest to reopen  #744 and regarding it as feature request to allow network connection status at login screen like Gnome.

**Comment by plfiorini** [comment]
SDDM does not provide a unique user experience, instead it allows desktop environments to provide their user interface.
The comparison with GNOME is not appropriate because GDM is a display manager that is specific to GNOME and it only have one user interface where all this stuff can be shown.

There is nothing we can do in the core SDDM to provide you with network configuration.

Please ask to the developers of your favorite desktop environment to provide such feature in their SDDM theme.

**Comment by saidbakr** [comment]
@plfiorini  To clarify the issue, for example, if I meant by KDE, so I have to ask KDE theme developer or KDE developer in general for this issue, does it right?

**Comment by plfiorini** [comment]
@saidbakr If you use Plasma and you want to access network settings from its SDDM theme, the same way you can from the desktop environment, you should ask the KDE developers to implement that feature.

**Comment by saidbakr** [comment]
> @saidbakr If you use Plasma and you want to access network settings from its SDDM theme, the same way you can from the desktop environment, you should ask the KDE developers to implement that feature.

I don't think this is true. Simple, if I activate GDM3 on my Kubuntu, I will see the network status at the display manager. This may mean that it is not a KDE developers issue.

**Comment by christianhujer** [comment]
While the _user interface_ of network configuration may be desktop-specific (GNOME vs KDE for example), there are two issues here:
1. The desktop interface (GNOME, KDE, whatever) hasn't even been chosen yet in case the system provides multiple desktop environments in parallel.
2. System network connections are system-level, not desktop-level.

The inability of choosing a network connection means that SDDM is incapable of providing network login capabilities (LDAP, JumpCloud, etc) in remote situations to regular (non-root) users. There's a chicken-egg problem due to this: If I can't connect to the network, I don't get my user profile onto the machine, and if I don't have a user profile, I can't log in to my desktop to connect to the network. Even Windows provides this now. We used to be decades ahead of Windows…

Isn't there a sort of common interface to launch a GUI that can connect to Wi-Fi that the default desktop or selected desktop could provide before login? If not, can one be created and negotiated with GNOME, KDE, and other desktop projects?
