### ISSUE TITLE
bug: sddm login no longer registers the carriage returns after password entry (using kde under debian testing)

### ISSUE THREAD

**Issue by sebastienbailard** [sddm/sddm#1107]
I'm running debian testing. After apt-get update-ing my system, I can't login to kde using sddm, as sddm doesn't register the carriage return that follows my password.

(I'm guessing this is the effect of debian testing being a mixture of different versions of packages.)

Any ideas? Anything I should do to help report this bug or help people troubleshoot it? Any workarounds?

$ kf5-config --version
Qt: 5.11.2
KDE Frameworks 5.51.0
kf5-config: 1.0

dpkg-query -l | grep sdm
rc kde-config-sddm 4:5.14.3-1 ...
ii sddm 0.18.0-1 ...
ii sdddm-theme-debian-maui 0.18.0-1  ...

**Comment by Pointedstick** [comment]
Does this happen when you try to log in immediately after the login screen appears, or after you wait more than 50 seconds such that the UI disappears and you need to make it re-appear by wiggling the mouse or typing?

**Comment by davidedmundson** [comment]
The Breeze theme has a big login button, so you should still be able to log in, and then you can confirm if enter works everywhere else.

Your potential problems are:
 - you have some custom SDDM theme which is broken
 - your keyboard layout is screwed in your X config
 - enter is working fine, it's just not doing anything due to a different issue.

Probably worth checking journald for the latter.

**Comment by Pointedstick** [comment]
Sounds like a buggy theme. Can you close this issue please? Thanks!

**Comment by sebastienbailard** [comment]
Mostly it was kde-plasma-desktop not existing.  The theme works.

Thanks, issue closed.

**Comment by PartialVolume** [comment]
One year on and I'm seeing this issue on the latest KDE Neon. Due to the nature of this bug and whether you experience it depends on your 'technique' in entering your password.

So assuming your screen has auto locked/blanked and you want to wake up the screen and log in you can do this in three subtly different ways. One of those three ways will show this bug the other two ways won't show the bug.

The three techniques for logging in.

1. You move the mouse, the login screen appears, you position the mouse cursor in the password box and click left. You type the password and hit return..... Then nothing happens. This technique shows the bug.

2. You move the mouse, the login screen appears, you DO NOT click in the password box but instead immediately start typing the password and hit return. You're now logged in!  This method does not show the bug.

3. You move the mouse, the login screen appears, you either click left in the password box OR NOT, it doesn't matter which, you enter your password and DO NOT hit return. You click left on the login button. Your're now logged in!  This technique does not show the bug.

So I would be interested in anybody that does not have this problem, to try using precisely the steps described in technique 1 above and let's us know whether you can reproduce this bug.

**Comment by Pointedstick** [comment]
The bug you're experiencing is a KDE bug: https://bugs.kde.org/show_bug.cgi?id=415130
