### ISSUE TITLE
No password input when screen was locked due to inactivity

### ISSUE THREAD

**Issue by karmux** [sddm/sddm#1308]
When screen locks due to inactivity then login screen does not show password input. Also it doesn't show my name. Only time and date are visible on the login screen. I have to press Ctrl+Alt+F2 and then Ctrl+Alt+F1 to get password input and my name visible. If I manually lock the screen then this bug doesn't happen.

It has been bothering me for years with every computer I've been using and it's still present with latest packages. I'm using KDE on Manjaro Linux.

**Comment by Pointedstick** [comment]
This is entirely controlled by the greeter theme itself. The Breeze theme used to have this bug, but it was fixed at some point in the last year or so. I strongly suspect that Manjaro's Breath theme-which is a--pointless fork of the Breeze theme--has not been updated to pick up the fix. Even better would be dropping the fork since the upstream Breeze theme is already capable of displaying a custom wallpaper, which as far as I can tell is the only change they've made.
