### ISSUE TITLE
sddm.conf.d/virtualkbd.conf has no effect?

### ISSUE THREAD

**Issue by plata** [sddm/sddm#1568]
I've tried to enable the virtual keyboard as described in https://wiki.archlinux.org/title/SDDM#Enable_virtual_keyboard. However, this didn't work.
Setting `InputMethod` in `/etc/sddm.conf` works.

Is this the intended behavior? If so, what's the purpose of `virtualkbd.conf`?

**Comment by aspiers** [comment]
Not sure why it doesn't work for you, but these describe the intended behaviour:

https://github.com/sddm/sddm/wiki/0.16.0-Release-Announcement#configuration

https://github.com/sddm/sddm/blob/e64a87d08c7c978c0a63e7ff3f02e3c3eed96746/src/common/ConfigReader.cpp#L145-L148

**Comment by plata** [comment]
`/etc/sddm.conf` contains an empty `InputMethod=`. As this is loaded last, it overwrites `virtualkbd.conf`. I can't imagine that this is what the package maintainer intended to do. However, I don't currently even understand where `/etc/sddm.conf` comes from.

**Comment by stanczew** [comment]
Arch doesn't package `/etc/sddm.conf` since almost 5 years:
https://github.com/archlinux/svntogit-packages/commit/10879d1c4bc119e3de471f130698b6ffd61210e5
Any settings in `/etc/sddm.conf` that you didn't set yourself are leftovers from old configuration.

Current Arch package does indeed set `InputMethod=`, but it's done in `/usr/lib/sddm/sddm.conf.d/default.conf`:
https://github.com/archlinux/svntogit-packages/blob/packages/sddm/trunk/PKGBUILD#L66..L67
This file has lower priority than files in `/etc/sddm.conf.d`, so settings from `/etc/sddm.conf.d/virtualkbd.conf` will not be overwritten by it.

**Comment by plata** [comment]
It was on a fresh Manjaro installation. So it might be that it's packaged correctly in Arch but not in Manjaro.
