### ISSUE TITLE
Login loop when using fish as login shell

### ISSUE THREAD

**Issue by XYQuadrat** [sddm/sddm#1592]
When using `fish` as the user login shell, it is not possible to log in to KDE Plasma (X11) with sddm. After entering the correct password, the screen goes black for a short while and some logs (probably X Server startup stuff) flash. Afterwards, one is returned to the sddm login prompt.

**Steps to reproduce:**
1. Use `chsh -s /usr/bin/fish` to change the user login shell.
2. Log out.
3. Try to log in with the user where the login shell was changed.

I'm using version `0.19.0+p22.04+tunstable+git20220916.0023-0` from KDE Neon Unstable (upgraded to Ubuntu 22.04). Changing the login shell back to `bash` with `chsh -s /bin/bash` from a TTY resolves the issue. I have also set various environment variables in `fish` only. Potentially those could be related to the issue too; though most of them seem completely unrelated to `sddm` to me (e.g. `KDEHOME` or `CARGO_HOME`).

**Comment by mgunyho** [comment]
I am having this exact same, but with `xonsh`.

Which distro are you using? I am on openSUSE and I think I know what the problem is: based on the output of `journalctl -b`, Plasma is launched by `sddm-helper` with the command `/usr/etc/X11/xdm/Xsession \"/usr/bin/startplasma-x11\"`. So it's using an `Xsession` script from xdm instead of sddm! I suppose that script is quite old, and doesn't support fish (nor xonsh). The `Xsession` script that comes with sddm (see [here](https://github.com/sddm/sddm/blob/37a39d07ce14251bbe643f1ddfcbdd4684859927/data/scripts/Xsession), on my machine it's located in `/usr/share/sddm/scripts/Xsession`) should support `fish`, though not `xonsh`.

**Comment by Saulimedes** [comment]
This is still reproducible in opensuse tumbleweed. The screen goes blank after login after switching to a non posix shell or adjusting the local .bashrc to drop into it like:

```
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]
then
	exec fish
fi
```

**Comment by Dieken** [comment]
Got this issue too on Slackware current,  the script `/usr/share/sddm/scripts/Xsession` is outdated, it doesn't source `/etc/profile` which brings many important environment variables.

The `Xsession` at https://github.com/sddm/sddm/blob/37a39d07ce14251bbe643f1ddfcbdd4684859927/data/scripts/Xsession#L29  is correct, fixed by https://github.com/sddm/sddm/commit/cf65e99eb8abfe2ee1ef7e2f7dc43862e83bf0ab, unfortunately that fix isn't released yet.

@aleixpol  @Vogtinator  could you release 0.20.0 or 0.19.1 to include that fix?

**Comment by mufeedali** [comment]
Shouldn't this be fixed in 0.20.0?

**Comment by JamesMcMahon** [comment]
Broken on OpenSuse Tumbleweed, SDDM version `0.20.0-3.2`.

**Comment by mufeedali** [comment]
@JamesMcMahon

Try this:

> In the meantime, openSUSE Fish users can add export -n PROFILEREAD to ~/.profile

From https://github.com/sddm/sddm/issues/1391

**Comment by JamesMcMahon** [comment]
> @JamesMcMahon
> 
> Try this:
> 
> > In the meantime, openSUSE Fish users can add export -n PROFILEREAD to ~/.profile
> 
> From #1391

Thanks, I ended up just keeping bash as my default shell and set Konsole to use Fish by default.

**Comment by korewaChino** [comment]
Broken on Fedora 40, `sddm-0.21.0-4.fc40.x86_64`

**Comment by svenjacobs** [comment]
> @JamesMcMahon
> 
> Try this:
> 
> > In the meantime, openSUSE Fish users can add export -n PROFILEREAD to ~/.profile
> 
> From #1391

Unfortunately this didn't work for me.

I'm using openSUSE Tumbleweed (20240701). 
sddm `0.21.0-3.1`. fish `3.7.1`.

**Comment by Vogtinator** [comment]
Tumbleweed has the fix for fish backported for some time already. You're most likely hitting a different issue.

**Comment by svenjacobs** [comment]
> Tumbleweed has the fix for fish backported for some time already. You're most likely hitting a different issue.

You're right. Weird, now it's working. Don't know what has changed 🤷🏼

**Comment by XYQuadrat** [comment]
I can confirm that this works for me with sddm `0.21.0-0zneon+22.04+jammy+release+build1`. Given that [the underlying problem I had has been fixed](https://github.com/sddm/sddm/issues/1592#issuecomment-1565455750), and that Vogtinator says that cases of it not working are mostly likely hitting a different problem (which should get their own, separate issue), I'll close this.
