### ISSUE TITLE
 SDDM Cannot Launch Plasma-wayland Session

### ISSUE THREAD

**Issue by Giger22** [sddm/sddm#1795]
Hello, I cannot log in to a wayland session using sddm. It just shows blank screen and goes back to the login screen. 

Using command:
cat ~/.local/share/sddm/wayland-session.log
I got following log:

> dbus-daemon[25371]: [session uid=1000 pid=25371] Activating service name='org.kde.KSplash' requested by ':1.0' (uid=1000 pid=25372 comm="/usr/bin/startplasma-wayland")
> dbus-daemon[25371]: [session uid=1000 pid=25371] Activating service name='org.freedesktop.portal.Desktop' requested by ':1.4' (uid=1000 pid=25385 comm="/usr/bin/ksplashqml")
> kdeinit5: preparing to launch '/usr/lib/kf5/klauncher'
> kdeinit5: Launched KLauncher, pid = 25394, result = 0
> dbus-daemon[25371]: [session uid=1000 pid=25371] Activating service name='org.freedesktop.portal.Documents' requested by ':1.5' (uid=1000 pid=25392 comm="/usr/lib/xdg-desktop-portal")
> dbus-daemon[25371]: [session uid=1000 pid=25371] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.6' (uid=1000 pid=25399 comm="/usr/lib/xdg-document-portal")
> dbus-daemon[25371]: [session uid=1000 pid=25371] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
> dbus-daemon[25371]: [session uid=1000 pid=25371] Successfully activated service 'org.freedesktop.portal.Documents'
> fusermount3: failed to access mountpoint /run/user/1000/doc: Permission denied
> error: fuse init failed: Can't mount path /run/user/1000/doc
> dbus-daemon[25371]: [session uid=1000 pid=25371] Activating service name='org.freedesktop.impl.portal.desktop.gtk' requested by ':1.5' (uid=1000 pid=25392 comm="/usr/lib/xdg-desktop-portal")
> 
> (kwin_wayland:25382): Gtk-WARNING **: 23:24:57.548: cannot open display:
> 
> (kwin_wayland:25424): Gtk-WARNING **: 23:24:57.626: cannot open display:
> 
> (kwin_wayland:25428): Gtk-WARNING **: 23:24:57.703: cannot open display:
> 
> (kwin_wayland:25430): Gtk-WARNING **: 23:24:57.783: cannot open display:
> 
> (kwin_wayland:25432): Gtk-WARNING **: 23:24:57.859: cannot open display:
> 
> (kwin_wayland:25434): Gtk-WARNING **: 23:24:57.936: cannot open display:
> 
> (kwin_wayland:25436): Gtk-WARNING **: 23:24:58.013: cannot open display:
> 
> (kwin_wayland:25438): Gtk-WARNING **: 23:24:58.089: cannot open display:
> 
> (kwin_wayland:25440): Gtk-WARNING **: 23:24:58.165: cannot open display:
> 
> (kwin_wayland:25442): Gtk-WARNING **: 23:24:58.243: cannot open display:
> 
> (kwin_wayland:25444): Gtk-WARNING **: 23:24:58.322: cannot open display:
> The Wayland connection broke. Did the Wayland compositor die?
> The Wayland connection broke. Did the Wayland compositor die?
> kdeinit5: Communication error with launcher. Exiting!
> Error: could not determine $DISPLAY.
> Error: Can not contact kdeinit5!
> org.kde.startup: "kdeinit5_shutdown" () exited with code 255
> startplasma-wayland: Shutting down...
> startplasmacompositor: Shutting down...
> startplasmacompositor: Done.

I can start wayland session executing "dbus-run-session startplasma-wayland" command but only through bash it does not work If I run it in tty.

**Comment by eclipseo** [comment]
I have the same issue on Fedora 39. Nvidia driver.
In Journalctl I have:
```
sept. 21 17:06:00 Cassini sddm-greeter[2146]: Loading file:///usr/share/sddm/themes/01-breeze-fedora/Main.qml...
sept. 21 17:06:00 Cassini sddm-helper-start-wayland[2143]: "kwin_xkbcommon: XKB: inet:323:58: unrecognized keysym \"XF86EmojiPicker\"\nkwin_xkbcommon: XKB: inet:324:58: unrecognized keysym \"XF86Dictate\"\n"
sept. 21 17:06:00 Cassini audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=>
sept. 21 17:06:00 Cassini systemd[1]: Started systemd-localed.service - Locale Service.
sept. 21 17:06:00 Cassini systemd[1]: Starting systemd-localed.service - Locale Service...
sept. 21 17:06:00 Cassini audit: BPF prog-id=81 op=LOAD
sept. 21 17:06:00 Cassini audit: BPF prog-id=80 op=LOAD
sept. 21 17:06:00 Cassini audit: BPF prog-id=79 op=LOAD
sept. 21 17:05:59 Cassini sddm-helper-start-wayland[2143]: "OpenGL vendor string:                   AMD\nOpenGL renderer string:                 AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.54, 6.5.4-300.fc39.x8>
sept. 21 17:05:59 Cassini sddm-helper-start-wayland[2143]: "kf.globalaccel.kglobalacceld: No desktop file found for service  \"org.kde.kcalc.desktop\"\n"
sept. 21 17:05:59 Cassini dbus-broker-launch[2150]: Ready
sept. 21 17:05:59 Cassini systemd[2130]: Started dbus-broker.service - D-Bus User Message Bus.
sept. 21 17:05:59 Cassini dbus-broker-launch[2150]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
sept. 21 17:05:59 Cassini dbus-broker-launch[2150]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
sept. 21 17:05:59 Cassini dbus-broker-launch[2150]: Service file '/usr/share//dbus-1/services/org.kde.plasma.Notifications.service' is not named after the D-Bus name 'org.freedesktop.Notifications'.
sept. 21 17:05:59 Cassini dbus-broker-launch[2150]: Service file '/usr/share//dbus-1/services/org.kde.dolphin.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'.
sept. 21 17:05:59 Cassini dbus-broker-launch[2150]: Service file '/usr/share//dbus-1/services/imsettings-daemon.service' is not named after the D-Bus name 'com.redhat.imsettings'.
sept. 21 17:05:59 Cassini dbus-broker-launch[2150]: Service file '/usr/share//dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.
sept. 21 17:05:59 Cassini systemd[2130]: Starting dbus-broker.service - D-Bus User Message Bus...
sept. 21 17:05:59 Cassini systemd[2130]: Created slice session.slice - User Core Session Slice.
sept. 21 17:05:59 Cassini audit[2105]: USER_START pid=2105 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:xdm_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_unix,pam_systemd acct="sddm" exe="/u>
sept. 21 17:05:59 Cassini systemd[1]: Started session-c1.scope - Session c1 of User sddm.
sept. 21 17:05:59 Cassini audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=user@988 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi>
sept. 21 17:05:59 Cassini systemd[1]: Started user@988.service - User Manager for UID 988.
```

**Comment by eclipseo** [comment]
@Giger22 What's your shell? Bash or something else?

**Comment by MartinJrgsn** [comment]
I experienced the same issue on both Arch and Gentoo.
I installed Plasma and used SDDM to launch it.
While using this configuration everything worked fine until i tried installing distrobox, installing and running steam. It managed to launch and was installing the updates (with a really small scaling), when it completely vanished. So in both instances (arch and gentoo), I quit steam with CTRL+C and exited the distrobox container.

The next time I started my PC, I experienced problems.
On Arch systemd got stuck trying to launch plymouth, while on gentoo SDDM managed to launch.

Trying to login to Plasma (Wayland) I was met with a black screen with an underscore in the top corner of the screen. Switching through the different TTYs, I found a black screen with a cursor.

After searching for a while, I came across this issue: https://github.com/sddm/sddm/issues/1335#issuecomment-743931325

Since I had managed to get plasma to launch with 
`$ dbus-run-session startplasma-wayland`
I knew that I wanted to tell SDDM or Lightdm (that I installed trying to get plasma to launch) that it should use this command to launch.

So changing the file /usr/share/wayland-sessions/plasmawayland.desktop, and editing the Exec field like so:
```
[Desktop Entry]
#Exec=/usr/lib64/libexec/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland
Exec=/usr/bin/dbus-run-session /usr/bin/startplasma-wayland
```

I just managed to get lightdm to launch Plasma (Wayland). I will now switch my display-manager back to SDDM to check if SDDM manages to launch Plasma (Wayland) aswell.

EDIT:
I was unable to simply switch the `DISPLAYMANAGER="lightdm"` to `DISPLAYMANAGER="sddm"` in the `/etc/conf.d/display-manager ` file. When trying to launch Plasma (Wayland) I was again met with a black screen with a cursor.

There is also this strange side-effect of using /usr/bin/dbus-run-session in the [Desktop Entry] field in the plasmawayland.desktop file, in that my keyboard needs to be re-seated in order to function. Not sure what this means though.

**Comment by Giger22** [comment]
> @Giger22 What's your shell? Bash or something else?

Bash.

I solved this issue following this instructions:
https://www.reddit.com/r/artixlinux/comments/133a1fz/kde_wayland_on_dinit_not_working/
