### ISSUE TITLE
login/invoke pam without entering password(howdy/face id authentication automaticly)

### ISSUE THREAD

**Issue by littleblack111** [sddm/sddm#1966]
since i have [howdy](https://github.com/boltgolt/howdy) setup. i wanna auto login without pressing enter on my keyboard. is that possible

**Comment by Vogtinator** [comment]
The same as #284 from a technical PoV.

**Comment by MrGrymReaper** [comment]
@Vogtinator Please re-open this issue. They aren’t the same from a technical point of view.

There’s also currently a known issue with Howdy and SDDM, namely a login hang due to no confirmation back.

On top of this the previously linked issue as part of duplication, for a reason to close is a different piece of software.

The software fprint handles fingerprint biometric authentication, while Howdy handles facial recognition biometric authentication.

**Comment by Vogtinator** [comment]
> They aren’t the same from a technical point of view.

Async PAM will fix this for any kind of biometric (and some non-biometric) options including fprint and howdy.

**Comment by MrGrymReaper** [comment]
So should a new issue be opened then for the login hang with howdy due to lack of confirmation back?

**Comment by Vogtinator** [comment]
IMO no, I think if fprintd is properly supported howdy should just work as well.
