### ISSUE TITLE
change default cursor position to the password-input-box

### ISSUE THREAD

**Issue by ljrk0** [sddm/sddm#254]
This is just a small neat enhancement. But it would be much cooler if u could just type rightaway instead of first clicking the password-field
[Suggestion] [Enhancement]

**Comment by Ilya87** [comment]
This bug appears again in Arch Linux x86_64 with Qt 5.5 and git ver. d42700a31375d5c82359df63fafe03a5eaa824f6

**Comment by jpsinthemix** [comment]
Going through commits I found that this issue was re-introduced in commit https://github.com/sddm/sddm/commit/947b8d19550df36bb992ba864f9d2f70423e2664

Here is a simpler patch which "fixes" the problem, but may not be correct for multi-screen setups, not sure:

--- sddm-0.13.0.old/src/greeter/GreeterApp.cpp  2015-11-04 14:09:15.000000000 -0500
+++ sddm-0.13.0.new/src/greeter/GreeterApp.cpp  2015-11-15 07:04:18.251524653 -0500
@@ -201,6 +201,9 @@ namespace SDDM {
         // show
         qDebug() << "Adding view for" << screen->name() << screen->geometry();
         view->show();
+
+        if (QGuiApplication::primaryScreen() == screen)
+            view->requestActivate();
     }
 
     void GreeterApp::removeViewForScreen(QQuickView *view) {

The regression is due to no view being given keyboard focus.
Hopes this helps.

Thanks for the DM.
