### ISSUE TITLE
textColor property never used in ComboBox

### ISSUE THREAD

**Issue by int-ua** [sddm/sddm#298]
So it doesn't affect anything when trying to change it in a theme.

**Comment by phavx** [comment]
This still isn't fixed and sadly I just spend 40 minutes trying for nothing :(

**Comment by jleclanche** [comment]
@phavx Do you have an example of a theme with a failure case?

**Comment by phavx** [comment]
Only my own one which I'm working on, but the problem is basically that this

    ComboBox {
                            id: session
                            width: parent.width; height: 30
                            font.pixelSize: 14
                            font.family: "Roboto Slab"
                            color: "#444852"
                            borderColor: "#383c45"
                            focusColor: "red"
                            hoverColor: "yellow"
                            textColor: "green"

                            arrowIcon: "down.svg"

                            model: sessionModel
                            index: sessionModel.lastIndex

                            KeyNavigation.backtab: password; KeyNavigation.tab: layoutBox
                        }


doesn't work. The "yellow" for hover gets applied and also the "red" for focus, however the "green" for the text itself doesn't work and stays on the default blackish color. (Besides that, also trying to find out how the change the background color in the expanded dropdown, but not that important right now).
