### ISSUE TITLE
Arabic translation and layout

### ISSUE THREAD

**Issue by SafaAlfulaij** [sddm/sddm#329]
This is the Arabic translation file: https://www.dropbox.com/s/wkrfwl6mjhyx9ty/ar.ts?dl=1
Sorry but I don't know GIT very well to make pull request.

Another thing should be done with this translation. Arabic is a RTL language and therefore the UI should be RTL.
I've tried this line in GreeterApp.cpp but it didn't work..
        setLayoutDirection(QLocale::system().textDirection());

Thanks for this great DM! :-)

**Comment by fduraibi** [comment]
Yes, we need that

@SafaAlfulaij Thanks you for the translation. i wish it get integrated.
Will it just work if I placed the files into the translation folder? or the list of languages is hard coded somewhere else?

**Comment by plfiorini** [comment]
Translation merged.
The layout could probably be set by the themes, I'll figure it out later.

**Comment by plfiorini** [comment]
@fduraibi you need to build sddm from master to have the translation installed on your system, then just edit /etc/environment and put:

```
LC_ALL=ar_AR
```

This is what I get:

http://imgur.com/a/e51gu

Is it good or do we need to do something more?

**Comment by plfiorini** [comment]
The clock looks weird though

**Comment by plfiorini** [comment]
When using the ar locale, the password prompt cursor is RTL though when I enter text the layout switches to italian and the field becomes LTR which is normal since the input should not be LTR.

However I realize now that probably the widgets should be reverse.

This is what I get enabling layout mirroring with the maui theme:

http://imgur.com/bQdrREm

**Comment by fduraibi** [comment]
@plfiorini Looks good to me, thank you.
