### ISSUE TITLE
Provide access to "password" field from getpwent for themes

### ISSUE THREAD

**Issue by mobius3** [sddm/sddm#380]
The `pw_passwd` field from `getpwent()` provides the user password encrypted, an * or an x in case password is stored in /etc/shadow. For users that are allowed to login without an password, this field is empty.

Users that can login without password are useful for HTPCs to switch, say, from Kodi/XBMC to Netflix, etc (exactly my setup, as you can figure :)

Having access to this password field would let themes decide if a password box should be shown.

If providing the contents of this field is too much, maybe a boolean such as `hasPassword` or `canLoginWithoutPassword` (in cases where this information might come from elsewhere in the future, like pam).

**Comment by plfiorini** [comment]
This doesn't seem to be true on my ArchLinux virtual machine.
Issuing a passwd -d -l plfiorini result in my account having "x" on pw_passwd just like before.

**Comment by plfiorini** [comment]
When my account doesn't have a password /etc/shadow shows a ! instead of the hashed password, but /etc/passwd keeps having x.

However according to man 5 passwd pw_passwd might be empty, when it's x the password comes from /etc/shadow which can then be ! for empty password. But I'm not sure how can we get that info from sddm.

This means that on some setups (when /etc/shadow is used) your PR #381 won't work

**Comment by plfiorini** [comment]
Even if the password prompt will still be shown when shadow is used, you'll be able to login with an empty password (just press enter).
