### ISSUE TITLE
Guest login

### ISSUE THREAD

**Issue by poidl** [sddm/sddm#388]
I would like to have a "Guest-login", and I saw there is an entry "Guest-login" on the TODO page [https://github.com/sddm/sddm/wiki/TODO], which is about half a year old.

In KDM, I used to set up a home directory on a temporary file system on kdm start (as root before the login dialog appears), and cleaned/recreated it after each logout. I used the Xreset script for that. The following post in the Arch forum explains details: 

https://bbs.archlinux.org/viewtopic.php?id=192891

I'm not a Linux expert, so this method might be out of date? If it isn't, may I suggest that, until the proper "Guest-login" is finished, to make something analogous to 
/usr/share/config/kdm/Xreset,
such that we can use this method in the meantime?

Thank you very much for your great work! 
Stefan

**Comment by Raffarti** [comment]
xguest login works afaik.

**Comment by poidl** [comment]
Isn't this a SELinux feature? Uff, that sounds complicated....anyways,
thanks for the suggestion.

**Comment by Raffarti** [comment]
If you have troubles with audio/network/etc in xguest check user groups.

**Comment by poidl** [comment]
Xguest is not the way to go for me. I wait until the sddm guest login from
the wishlist is available, or alternatively Xreset. Until then I use kdm.
Thanks again, Stefan

**Comment by poidl** [comment]
I just saw that 
/usr/share/sddm/scripts/Xstop
is now available in 0.12.0. Seems to work well for my purpose. THANK YOU!

**Comment by callegar** [comment]
@poidl (and the sddm developers)

The concepts in https://bbs.archlinux.org/viewtopic.php?id=192891 do not appear to be fully applicable to sddm.

- If you have a guest user that is a system user, sddm will not show it
- the Xstop script does not seem to get any USER environment variable, so you do not know when to clear the guest user workspace, because you do not know what session is being closed.

Any idea?

**Comment by poidl** [comment]
Yes I remember the system user not showing up. But you can change that in the sddm config. There are (or at least were at some point) keywords in sddm.conf like 'MaximumUid', 'MinimumUid' which e.g. would let you define a range.

 
Regarding the clear the guest: if it has a fixed username, you could remove/add the corresponding account at every logout, not just the guest user. Maybe not the best solution, I don't know...

-----Original message-----

**Comment by callegar** [comment]
The problem is that in most systems (debian, ubuntu?) UID 999 is taken by some systemd stuff, so any system user will get something < 999, meaning that if `MinimumUID` is set to let the guest user in, it will also show the systemd user.

Problem with removal is:
- Login as foo
- Switch to guest
- Switch back to foo
- Logout from foo
if on logout from foo, one cannot check the user who is logging off and unconditionally deletes the guest home, trying to switch back again to guest will now freeze the desktop.

So, I think that some more support from sddm is needed.

**Comment by poidl** [comment]
>>if on logout from foo, one cannot check the user who is logging off and unconditionally deletes the guest home, trying to switch back again to guest will now freeze the desktop.

 
Ah, good point! Maybe one could check with loginctl? Hmm, I guess my knowledge about system administration is very limtied.

 
Anyways, I still think this would be a great feature! Thanks for looking into it!

-----Original message-----
