### ISSUE TITLE
Add an option to prevent greeter from building a full user model

### ISSUE THREAD

**Issue by louen** [sddm/sddm#479]
When working on a machine on which user authentication is through a network server (e.g. NIS), the greeter screen takes a lot of time to start up (~10-15 min in my case), leaving the screen blank.

It seems to be caused by the greeter building a UserModel by repeated calls to `getpwent()`. On a system with many users and each call to `getpwent()` querying the network server, it makes the login process unresponsive.

Along with the option not to display the full user list but a login/pw text box (see #406 or #450) there should be a way to avoid building the full user list and check user name only after user input.

**Comment by jleclanche** [comment]
Dup of #281 in not so many words. If there's further optimization that can be done, let me know and reopen.

**Comment by plfiorini** [comment]
Not exactly a duplicate. Disabling the avatars is a partial fix to this, we also want to avoid querying the network server with ``getpwent()``

I started a patch this morning. The patch moves the population to a slot which insert a user at a time; the slot is also called after a 200ms timeout but I'd like to try with a thread. It doesn't sort the users list anymore, this can be done with a sort proxy model.

**Comment by plfiorini** [comment]
A sysadmin would need to edit sddm.conf ti disable users listing which is equivalent to edit the settings to choose a theme that doesn't show them by design, hence I think that this setting is useless.

**Comment by jleclanche** [comment]
OK let's reopen then.

**Comment by plfiorini** [comment]
To summarize:

- If your setup has tons of users with remote homes you should edit sddm.conf and select a theme that doesn't show the users list
- We can make the UsersModel more efficient but I bet it won't completely fix the issue, to fix it the best option is still the bullet point above.

**Comment by greyhare** [comment]
Best I can tell, in 0.13.0 at least, getpwnam is called for every detected user regardless of whether or not the theme asks for it. I don't see anything in the code that does lazy evaluation. So even though I'm using the Maldives theme, which doesn't have a user list, SDDM is still trying to mount every home directory it can, specifically during an exists() call.

I've got a fix in my fork which adds a Users.ScanHomeDirs option (default true, matching current behavior), and will test it when I get back to work where the problem is. Once verified, I'll open a pull request. By putting this in Users and not Theme (where EnableAvatars is) should allow other non-theme code to use the setting if needed.

Of course, in my case, EnableAvatars would be a good enough workaround, but it is not in the latest stable release.

**Comment by Vogtinator** [comment]
I hit this issue every time sddm starts with a cold NSS cache. Sometimes it takes two minutes with a black screen.

I suggest to add an option for the theme to specify that it can work with an empty UserModel and then just skip filling the UserModel altogether, once it found more than the avatar threshold.
