### ISSUE TITLE
Passwordless Login

### ISSUE THREAD

**Issue by MoizesFerreira** [sddm/sddm#505]
I have two user accounts (mine and a guest, so that my son can use my computer without messing my stuff). I can't find a way to login the guest account. It is passwordless... 

"passwd --delete guest_account"

I am not talking about autologin. It is easy to setup. I want to login a passwordless account. I can do it with slim (haven't tried lightdm yet) but not with sddm. Can it be done? Thanks!

**Comment by plfiorini** [comment]
Did you press enter with an empty password?

**Comment by plfiorini** [comment]
No answer, closing

**Comment by mirh** [comment]
Last time I tried (two months ago) it just didn't work. 
Perhaps @likewhoa might still be interested to investigate

**Comment by likewhoa** [comment]
removing the password on the user allows login in SSDM when the desktop is locked manually or via a screensaver, but this is not a real solution to have a user with no password. Anyways, for those interested you have to run 
```
passwd --delete username
```
This issue should remain OPEN until we can allow password-less logins in SSDM as it was supported in KDM, this is a valuable feature for livecds.

**Comment by MoizesFerreira** [comment]
@plfiorini, I was away for a few days, but I tried to login using an empty password and did not work

**Comment by likewhoa** [comment]
@plfiorini do reopen ticket as empty passwords are very in common in a real world environment. There should be an option  in settings to allow password-less login instead or telling users they need to delete their password in order to login without one.

**Comment by vincentdephily** [comment]
Agreed, a config item listing users allowed to login without a password is sorely needed.

The workaround of deleting a user's password is not great because the two should be orthogonal, and because the trick is not really discoverable. I also suspect that it won't work unless the distribution has added the non-standard 'nullok' option to pam. And if sddm isn't using pam, it should consider providing an option equivalent to pam's nullok, and have it default to false.

**Comment by mikhailnov** [comment]
Any news?

**Comment by gshah30** [comment]
Even I need this. Any updates on this issue?
