### ISSUE TITLE
Mouse cursor size when using multimonitor.

### ISSUE THREAD

**Issue by CommanderAlchemy** [sddm/sddm#569]
I noticed that the mouse is enlarged when using more than one monitor.

I have currently {Left, Middle, Right} identical monitors.
Left Portrait 1080x1920.
Middle/Right Landscape 1920x1080.

When running only with one monitor the cursor is correct size, however when connecting my other monitors it appears enlarged.

**Comment by mdlui** [comment]
I can confirm, having the same issue.

**Comment by grawlinson** [comment]
I have 2 monitors (1440p in landscape + 1080p in portrait) and the mouse cursor size is approx 48 instead of the desired 24.

I'm happy to help with testing if need be.

**Comment by mikelui** [comment]
Looked into it a bit. I'm guessing this happens because the cursor is configured before the DPI can be set by the user: https://github.com/sddm/sddm/blob/develop/src/daemon/XorgDisplayServer.cpp#L300

E.g. I set my DPI in DisplayCommand, which would be used to size the cursor, but DisplayCommand is run after the cursor is created. IANAE w/ X11 or Plasma5 but this seems to be the likely case.

I don't have a dev environment setup right now, but I'd hope switching the order of setCursor->start and displayScript->start would fix this.

**Comment by mikelui** [comment]
On second examination I don't think that is the issue. The breeze cursor is handled separately

**Comment by dylif** [comment]
This continues to be an issue 4 years later.
For now, setting XCURSOR_SIZE to the correct value in /etc/environment works to an extent, but the larger cursor is still displayed while loading the greeter and while loading the user session.

Is there any way I could help to fix this issue?
