### ISSUE TITLE
0.14 Release Planned?

### ISSUE THREAD

**Issue by schijo** [sddm/sddm#619]
Are you considering to release 0.14 anytime soon?

I am using git but there are a number of fixes in git which have not been officially released as of yet but I find quite relevant. In particular (applies to 'maldives' theme): Blank login prompt, i.e not showing previous user and cursor focus is set correctly.
Other users might find this annoying as well (besides the security issue of showing previous user) so they might be interested in those fixes. Without those fixes they might be put off.

**Comment by ellisistfroh** [comment]
Nice asking! 

Kubuntu/Ubuntu 16.04 LTS and it's derivates will be released soonish (21.4.). There might be slight chance to get a freeze-exception (FFE). If this will close given bugs (sure we find some). 

Otherwise any patches will have to be sru-backported manually. And this is only possible via debdiff and their famous SRU process (Security-release-updates). Thinking Debian-users may o.c. also appreciate more frequent updates. Don't take be bad for saying so, please

Any chance?

**Comment by mrueg** [comment]
@plfiorini any plans for this? Would be nice to see a new release.

**Comment by greyhare** [comment]
So does this mean that Ubuntu LTS is the only distro that the SDDM project releases for? Gentoo is telling its KDE users to move to KDE 5/Plasma, and part of that is replacing KDM with SDDM, and SDDM's latest release was half a year ago, and missing a lot of features that are slated for 0.14, and have been merged for a long time.

Do we need to wait for a year and a half for Kubuntu/Ubuntu 18.04 LTS to open up before another release is considered? (And didn't Ubuntu ditch SDDM for LightDM?)

**Comment by jasontibbitts** [comment]
@greyhare How could you possibly get the impression that SDDM releases are tied to Ubuntu somehow?  Someone was hoping for a new release before some Ubuntu thing happens so that they wouldn't have to backport patches, but I see no comments in this ticket from anyone actually associated with the project.

**Comment by plfiorini** [comment]
I was very busy the past month so I couldn't release 0.14, if nothing changes it will be released next week.
