### ISSUE TITLE
PAM Changes are crashing SDDM on Kubuntu 16.04

### ISSUE THREAD

**Issue by shibumi** [sddm/sddm#637]
Hello,
I am running Kubuntu 16.04 with sddm   0.13.0-1ubuntu5. I have just added this line at the end of my pam common-session and common-auth:

`session        optional        pam_mount.so`

When I reboot, I just get a blackscreen.  My sddm-log looks like this:

```
Mai 20 13:47:17 lie systemd[1]: Starting Simple Desktop Display Manager...
Mai 20 13:47:17 lie systemd[1]: Started Simple Desktop Display Manager.
Mai 20 13:47:19 lie sddm[816]: Initializing...
Mai 20 13:47:19 lie sddm[816]: Starting...
Mai 20 13:47:19 lie sddm[816]: Adding new display on vt 7 ...
Mai 20 13:47:19 lie sddm[816]: Display server starting...
Mai 20 13:47:19 lie sddm[816]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{217bdaa4-9e7d-4b83-a2da-3e74d6b7794b} -background none -noreset -displayfd 17 vt7
Mai 20 13:47:22 lie sddm[816]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
Mai 20 13:47:22 lie sddm[816]: Display server started.
Mai 20 13:47:22 lie sddm[816]: Socket server starting...
Mai 20 13:47:22 lie sddm[816]: Socket server started.
Mai 20 13:47:22 lie sddm[816]: Greeter starting...
Mai 20 13:47:22 lie sddm[816]: Adding cookie to "/var/run/sddm/{217bdaa4-9e7d-4b83-a2da-3e74d6b7794b}"
Mai 20 13:47:22 lie sddm-helper[996]: [PAM] Starting...
Mai 20 13:47:22 lie sddm-helper[996]: [PAM] Authenticating...
Mai 20 13:47:22 lie sddm-helper[996]: [PAM] returning.
```

`Mai 20 13:47:22 lie sddm-helper[996]: [PAM] returning.` is the last line of the log.. 
I think it has something todo with: https://github.com/sddm/sddm/issues/629

I have also tried to use different themes for sddm. But without success.

**Comment by nkovacne** [comment]
Same here. I managed to get this working by commenting out:

`@include common-session`

and including all the content of `common-session` except the `pam_mount.so` line at `/etc/pam.d/sddm-greeter`, but when users close their sessions pam_mount is unaware so their logout and mountpoints don't get unmounted.

**Comment by plfiorini** [comment]
Please reopen if you still have issues.

**Comment by gelin** [comment]
KDE Neon has sddm 0.14.0 (0.14.0-1~2.gbpf70012+16.04+xenial+build8), however, the issue is reproduced when pam_mount tries to mount LUKS partitions (so the password is required).
Bind mounts works well.

**Comment by pterrien** [comment]
Hi,
I've run through this issue, too, on a fresh install of debian testing (buster), with **sddm 0.18.0-1**.

# Issue description
## symptoms
* Black screen with a mouse pointer, but no possible interaction (left/right mouse click, keyboard)
* TTYs are accessible
* `systemctl stop sddm && startx`allows me to get a working KDE Plasma environment though
## context
* sddm works correctly until I install *pam_mount* (*libpam-mount* for debian), **and** I add a volume in *pam_mount* configuration, such as:
  ```
  <volume fstype="cifs" server="server1.ad.lan" options="domain=MYDOMAIN,vers=3.0" path="data" mountpoint="~/mnt/server1/data" />
  ```
To be more precise:
* with the default *pam_mount* configuration (ie with no volume), *sddm* will display correctly
* adding a volume to the *pam_mount* config, then `systemctl restart sddm` will trigger the symptoms described above
* removing the volume from *pam_mount* config, then `systemctl restart sddm`, will make *sddm* display correctly again

# Analysis
## logs
In *syslog*:
```
Jan 13 15:12:56 mycomputer sddm[2338]: Greeter starting...
Jan 13 15:12:56 mycomputer sddm[2338]: Adding cookie to "/var/run/sddm/{b73b2904-3de9-46d5-b2ac-a407bd3be089}"
Jan 13 15:12:56 mycomputer sddm-helper[2349]: [PAM] Starting...
Jan 13 15:12:56 mycomputer sddm-helper[2349]: [PAM] Authenticating...
Jan 13 15:12:56 mycomputer sddm-helper[2349]: [PAM] returning.
Jan 13 15:12:56 mycomputer sddm[2338]: (pam_mount.c:568): pam_mount 2.16: entering session stage
Jan 13 15:12:56 mycomputer sddm-helper[2349]: [PAM] Preparing to converse...
Jan 13 15:12:56 mycomputer sddm-helper[2349]: [PAM] Conversation with 1 messages
Jan 13 15:22:53 mycomputer sddm[2338]: Signal received: SIGTERM
```

## humble assumptions... to be checked

As stated by @gelin:
> 
> 
> Same here. I managed to get this working by commenting out:
> 
> `@include common-session`
> 
> and including all the content of `common-session` except the `pam_mount.so` line at `/etc/pam.d/sddm-greeter`, but when users close their sessions pam_mount is unaware so when they logout their mountpoints don't get unmounted.

The issue seems to occur in `/etc/pam.d/sddm-greeter` , when performing `@include common-session`:
* *pam_mount* tries to mount the volume with the current user, which is *sddm*, and fails
  * in my case, that is perfectly normal, as the current user is the local *sddm* one, and it has no access to my AD domain member server

What I don't understand is:
  * when manually logging in with a local user (eg *root*), ie called by `/etc/pam.d/login`: this *pam_mount* failure is ignored, and login can proceed normally
  * when called by */etc/pam.d/sddm-greeter*: the *sddm*  process catches a SIGTERM, and terminates

## questions / possible solution
Is it possible for the *sddm* process to silently ignore errors that occur in `/etc/pam.d/common-session`?
Otherwise, is it possible to modify `/etc/pam.d/sddm-greeter`, by using conditions in `substack`instead of a simple `@include`?  
Sorry, I'm no expert with pam, I don't know if this makes sense to you...

Otherwise, in addition to @gelin proposal, below is another possible workaround:

# Other workaround: modify your *pam_mount* configuration
As stated before, the issue seems to occur because *pam_mount* tries to mount a share using the `sddm`user, which has no credentials for it.

So, basically, we just have to exclude the `sddm` user (and others, if needed), from mounting the share.
This uses the *extended user control* features in *pam_mount* ([link](http://pam-mount.sourceforge.net/pam_mount.conf.5.html#12)).

So, instead of defining the volume as below in `/etc/security/pam_mount.conf.xml`:
```
<volume fstype="cifs" server="server1.ad.lan" options="domain=MYDOMAIN,vers=3.0" path="data" mountpoint="~/mnt/server1/data" />
```
We can write (3 variants, adapt to your needs):
## Variant 1: allow only a given range of UIDs
```
<volume fstype="cifs" server="server1.ad.lan" options="domain=MYDOMAIN,vers=3.0" path="data" mountpoint="~/mnt/server1/data" uid="5000-999999999" />
```
## Variant 3: exclude a given range of UIDs
```
<volume fstype="cifs" server="server1.ad.lan" options="domain=MYDOMAIN,vers=3.0" path="data" mountpoint="~/mnt/server1/data">
  <not><user>0-4999</user></not>
</volume>
```
## Variant 3: exclude the sddm user only
```
<volume fstype="cifs" server="server1.ad.lan" options="domain=MYDOMAIN,vers=3.0" path="data" mountpoint="~/mnt/server1/data">
  <not><user>sddm</user></not>
</volume>
```

# Conclusion
Sorry for this long post, I hope it will be useful for people facing such issues.
Please let me know what you think about it!

Cheers.
