### ISSUE TITLE
Changes in  0.14.0 break existing configurations

### ISSUE THREAD

**Issue by lbeltrame** [sddm/sddm#680]
Commit 98bcb147acb793bf642e8a7bc9f69facb80e469a changed the configuration keys for VTs. This causes existing setups and distro-customized ones (like openSUSE, which runs SDDM on VT 7) to break, as the settings are no longer taken into account, and there is no upgrade path for existing configuration. 

Therefore, to ease deployments, I can see two possible scenarios:
1. MIgrate the existing configuration on startup;
2. Allow previous configuration keys, but deprecate them, print a warning, and remove them  in next_version+1.

Would this be possible?

**Comment by Vogtinator** [comment]
Another option would be to revert the name changes as they are merely stylistic and do not warrant such a breakage, IMO.

**Comment by plfiorini** [comment]
@lbeltrame we definitely need /etc/sddm.conf to go away and load vendor configuration from /usr/lib/sddm.conf.d and site configuration (written by the user) from /etc/sddm.conf.d - there is already an issue for that.

**Comment by lbeltrame** [comment]
IMO in this case the issue is not where the configuration is, but *what* is loaded. The configuration keys changed, so no matter where the file is loaded from, it won't get honored.

**Comment by plfiorini** [comment]
@lbeltrame my point is that downstream will and have to adjust their custom configuration but they can't now because user and distro settings are mixed in sddm.conf

**Comment by lbeltrame** [comment]
And our point, as distribution, is that we expect configuration file changes to be **at least** listed in release notes (I checked - there isn't any reference to this). We updated our package (just for testing, luckily)  and saw that it broke our setup. 

Any configuration file format change should be explicitly listed and a warning added in the release notes to warn people about changing their configs.

We'll now have to use hacks to change the existing configuration...

**Comment by tittiatcoke** [comment]
@plfiorini  The main issue is that a particular section header in the configuration file was changed. It does not read the old settings, so the update to 0.14.0 is no longer a simple drop-in as that it would no longer follow the old settings. So sddm will always startup as default on VT1, regardless of what the user or the distro has been indicating. 

The config file, wherever located, needs to be changed to reflect the changed key. Without the proper documentation this is quite hard and we only found out about this change when going through the commits. This is hardly distro or user friendly. Especially since that the change is merely an optical one.

**Comment by apachelogger** [comment]
Mh, yeah, the problem is that the key changed in a non-backwards compatible fashion. There should really just be a fallback lookup in place, or an automatic config migration upon startup.
Say I am a user who made sddm run on VT=3 because number 3 is my lucky number. Upon upgrade it will not use the setting anymore and run on VT whatever and since whatever is not my lucky number X11 will crash every other minute and I will be miserable and stop using Linux, and instead use Magenta.
Unfortunate thing which ought to be easy to avoid as a fallback is not expensive to implement, maintain or run. I should think :)

**Comment by plfiorini** [comment]
The faster way is to revert 98bcb147acb793bf642e8a7bc9f69facb80e469a - reverted in the develop branch but I cannot test it now and might have problems testing it this week due to QtCon.

Feel free to test it.

**Comment by plfiorini** [comment]
@rdieter this will also happen on Fedora

**Comment by lbeltrame** [comment]
Fedora, IIRC, runs the DM on VT 1, so I think this will impact less.

**Comment by plfiorini** [comment]
@lbeltrame might still cause issues to users that customized the config

@tpgxyz might also be of interest for OpenMandriva

**Comment by plfiorini** [comment]
As mentioned earlier, the fastest way to fix the issue would be to revert the commit and release a hot fix 0.14.1 with the revert, but still the configuration at startup should be implemented otherwise the issue will happen again.

Though releasing 0.14.1 with the revert and then reverting the revert in 0.15.0 sounds schizophrenic, probably better if distros with a custom configuration that has already built 0.14.0 would apply the revert on their tree.

**Comment by rdieter** [comment]
fyi, turns out fedora is (relatively) unaffected, we'd pulled in some post 0.13.0 patches awhile back (including the offending one here), and scripted configuration changes to adapt on upgrades.  Ironically, if this change is reverted, we(fedora) will likely also revert the revert (but that's not your or anyone else's problem).

**Comment by tpgxyz** [comment]
@plfiorini In case of OpenMandriva we are safe :)

**Comment by sudopluto** [comment]
I'm sorry if this is inappropriate, but I wanted to know if there are still plans to release sddm v0.14.1? Is there anything I could do to help?
