### ISSUE TITLE
Connect to WiFi on login screen

### ISSUE THREAD

**Issue by Mayzie** [sddm/sddm#744]
At the moment, SDDM (with KDE) does not connect to my WiFi connection when on the login screen like other desktop environments (GNOME, Windows). Reason being is that I have several web applications that start up on login that require an internet connection and screw up otherwise, so it would be nice to have it be able to connect before logging in.

**Comment by zilti** [comment]
That's really not something a *display* manager is supposed to do.

**Comment by eliasp** [comment]
@Mayzie Then you might want to configure your network connections as "System Connection", so it will be established on system boot/when the SSID is available independent from your user's login.

**Comment by adocampo** [comment]
Sorry to necrobump, but yet that isn't a feature a DM must control, it would be nice to have an icon to see if there are any working connection, wired or wireless. On corporate environments, a laptop can easy fail to login if the user hasn't connected the cable, is connected to a non-corporate wifi, or o... there are some situations that login can fail and perhaps an indicator like lightdm has will improve the user experience. I'm struggling to make linux the default desktop on the enterprise and little features like this makes the difference on the corporate environment.

**Comment by adocampo** [comment]
It's a pity SDDM developers ignore this issue. Is quite critical for the corporate environment, but if they target are home users, there is nothing to do here. Change your display manager to one more enterprise friendly, you can continue using Plasma as your desktop.

**Comment by plfiorini** [comment]
SDDM does not provide a unique user experience, instead it allows desktop environments to provide their user interface.
The comparison with GNOME is not appropriate because GDM is a display manager that is specific to GNOME and it only have one user interface where all this stuff can be shown.

There is nothing we can do in the core SDDM to provide you with network configuration.

@adocampo If you want to the network applet to be replicated in the Plasma SDDM theme, please file a feature request in their issue tracker.

Anyway, as @eliasp already said, the best way to make your computer connect at startup is to enable a service that connects to your network so it will be available even before SDDM starts.
