### ISSUE TITLE
Translations don't use same file structure

### ISSUE THREAD

**Issue by scootergrisen** [sddm/sddm#767]
I see the translations are not using the same file structure.

Some have just one `<context>` and some have three.

I don't know if it matters of which is correct is any but maybe make it the same.

**Comment by pmattern** [comment]
Basically this is due to the files of the various languages being updated to fit the source code at different times. After running `lupdate . -ts data/translations/*.ts` in the source code's root directory the structure is the same in all files.
(An invocation like this reveals some other problems affecting the translation which are a different story, though.)
