### ISSUE TITLE
SDDM is creating files in excess of ~50 GB

### ISSUE THREAD

**Issue by DaCo0k1eZ** [sddm/sddm#864]
I keep having issues of SDDM creating massive log files at ~/.local/share/sddm/ that will fill up the entirety of my SSD. They seem to just have the same thing printed about a million times. This is about the 3rd time this happened, last time the files logged nothing but wine errors from invalid function calls, but this time all it says is "ALSAAudioInput: Input/output error: Input/output error." Is there any way to disable logging in SDDM? I've updated SDDM a few times and the problem has persisted for the last several updates.

I'm running Arch Linux (4.12.5-1-ARCH) and SDDM (0.14.0-2, supposedly the latest version) if that helps. 

Here is a screenshot of the file in question and its contents: https://i.imgur.com/gy4gG9s.png

It seems to just continue writing to the file until it my SSD runs out of space.

**Comment by ekigwana** [comment]
See https://unix.stackexchange.com/questions/2574/where-do-x-error-messages-go. Basically you have a problem with you ALSA configuration and due to that, some program in the GUI frame continuously attempts to check / configure the audio while you are logged in. the xorg-xsession.log is a log capturing what you would otherwise not be able to see because you are not launching from a console. SDDM is not likely to be your issue.

**Comment by plfiorini** [comment]
Not a SDDM issue.
