### ISSUE TITLE
SDDM  0.17.0-3 doesn't show greater (black screen)

### ISSUE THREAD

**Issue by Xwang1976** [sddm/sddm#958]
On my archlinux system SDDM  0.17.0-3 doesn't show the greater (the screen is completely black) but it is possible to login blindly to the last used account.
SDDM 0.17.0-2 works perfectly.

**Comment by Xwang1976** [comment]
Maybe this bug is related to https://github.com/sddm/sddm/issues/959 because in my nvidia optimus system I'm using prime and I've the following lines in the Xsetup
`setxkbmap it

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

/bin/bash /usr/local/bin/toHDMI2Monitor.sh
`
(the last lone being a script which detect if an external monitor is connected and in such a case use xrandr to use only that monitor disabling the notebook internal screen.

**Comment by Vincent43** [comment]
It's Archlinux issue[1], not SDDM. You can fix this either by using an absolute path i.e. `/usr/bin/xrandr` instead of `xrandr` or change `DefaultPath=` to `DefaultPath=/usr/local/sbin:/usr/local/bin:/usr/bin` in` /usr/lib/sddm/sddm.conf.d/sddm.conf`

[1] https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/sddm&id=7527b9612b98b70a49942a6976ca1b273ad74d06

**Comment by antonio-rojas** [comment]
Yes, this is a downstream issue. However, the man pae is misleading and should be fixed. It says "DefaultPath: Default path to set after successfully logging in.". Doesn't say anything about sddm itself using it.

**Comment by jcrben** [comment]
@antonio-rojas did you open an issue or create a PR to fix the man page?
